#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Generate configuration files.
#======================================================================================================================

bf-echo "Creating PHP Apache2 configuration files..."
PHP_CONF=php.conf
bf-debug " .. ${PHP_CONF}"
bf-esh ${BF_TEMPLATES}/${PHP_CONF}.esh ${APACHE_CONF_D}/${PHP_CONF}
