#!/command/with-contenv bash

set -euo pipefail
export BF_E=`basename ${0}`


#======================================================================================================================
# Add environment variables.
#======================================================================================================================

# Library configuration
bf-env "PHP_LIB" "${BF_LIB}/php"

bf-env "APACHE_CONF_D" "/etc/apache2/conf.d"
